### ISSUE TITLE
Endpoint enrolment throws ziti controller login failure error

### ISSUE THREAD

**Issue by dineshsnf** [openziti/ziti-sdk-jvm#149]
Hi, I have created an endpoint and I am trying to enroll using the jwt as below:

        zitiContext = Ziti.enroll(ks,tokenStream.readAllBytes(),name);

The endpoint appears as registered in the console, however I get the following ziti controller login failure error:

        18:23:18.664 [main] INFO ZitiImpl - ZitiSDK version 0.18.5 @ddfeffc()
        18:23:20.208 [DefaultDispatcher-worker-1 @coroutine#1] DEBUG ziti-enroller - enrolling ctrl[https://23.22.127.125:443] name[3zIUuFGBC] method[ott]
        18:23:21.366 [DefaultDispatcher-worker-1 @coroutine#1] DEBUG ziti-enroller - received 4 certificates
        WARNING: An illegal reflective access operation has occurred
        WARNING: Illegal reflective access by org.openziti.net.nio.AsyncTLSSocketFactory (file:/Users/dineshs/.m2/repository/org/openziti/ziti/0.18.5/ziti-0.18.5.jar) to method java.net.Socket.getImpl()
        WARNING: Please consider reporting this to the maintainers of org.openziti.net.nio.AsyncTLSSocketFactory
        WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
        WARNING: All illegal access operations will be denied in a future release
        18:23:23.014 [DefaultDispatcher-worker-1 @coroutine#2] DEBUG ZitiContextImpl - 3zIUuFGBC[null]@https://23.22.127.125:443 transitioned to Loading
        18:23:23.072 [OkHttp https://23.22.127.125/...] DEBUG Controller - POST https://23.22.127.125/authenticate?method=cert session=null t[OkHttp https://23.22.127.125/...]
        18:23:23.419 [OkHttp https://23.22.127.125/...] DEBUG async-tls/1 - transitioning [initial -> connecting] 
        18:23:23.421 [DefaultDispatcher-worker-3 @coroutine#4] DEBUG async-tls/1 - transitioning [connecting -> handshaking] 
        18:23:23.537 [DefaultDispatcher-worker-3 @coroutine#4] DEBUG async-tls/1 - engine status = NEED_WRAP
        18:23:23.537 [DefaultDispatcher-worker-1 @coroutine#6] TRACE async-tls/1 - start reading loop()
        18:23:23.539 [DefaultDispatcher-worker-3 @coroutine#4] TRACE async-tls/1 - engine.handshakeStatus = NEED_WRAP
        18:23:23.541 [DefaultDispatcher-worker-3 @coroutine#4] TRACE async-tls/1 - engine.handshakeStatus = NEED_UNWRAP
        18:23:23.759 [DefaultDispatcher-worker-3 @coroutine#6] TRACE async-tls/1 - engine.handshakeStatus = NEED_TASK
        18:23:23.765 [DefaultDispatcher-worker-3 @coroutine#6] TRACE async-tls/1 - engine.handshakeStatus = NEED_UNWRAP
        18:23:23.766 [DefaultDispatcher-worker-3 @coroutine#6] TRACE async-tls/1 - engine.handshakeStatus = NEED_TASK
        18:23:23.771 [DefaultDispatcher-worker-3 @coroutine#6] TRACE async-tls/1 - engine.handshakeStatus = NEED_UNWRAP
        18:23:23.771 [DefaultDispatcher-worker-3 @coroutine#6] TRACE async-tls/1 - engine.handshakeStatus = NEED_TASK
        18:23:23.772 [DefaultDispatcher-worker-3 @coroutine#6] TRACE async-tls/1 - engine.handshakeStatus = NEED_UNWRAP
        18:23:23.772 [DefaultDispatcher-worker-3 @coroutine#6] TRACE async-tls/1 - engine.handshakeStatus = NEED_TASK
        18:23:23.773 [DefaultDispatcher-worker-3 @coroutine#6] TRACE async-tls/1 - engine.handshakeStatus = NEED_UNWRAP
        18:23:23.774 [DefaultDispatcher-worker-3 @coroutine#6] TRACE async-tls/1 - engine.handshakeStatus = NEED_TASK
        18:23:23.779 [DefaultDispatcher-worker-3 @coroutine#6] TRACE async-tls/1 - engine.handshakeStatus = NEED_WRAP
        18:23:23.780 [DefaultDispatcher-worker-3 @coroutine#6] TRACE async-tls/1 - engine.handshakeStatus = NEED_UNWRAP
        18:23:23.997 [DefaultDispatcher-worker-3 @coroutine#6] TRACE async-tls/1 - engine.handshakeStatus = NEED_UNWRAP
        18:23:23.998 [DefaultDispatcher-worker-3 @coroutine#6] TRACE async-tls/1 - engine.handshakeStatus = NOT_HANDSHAKING
        18:23:23.998 [DefaultDispatcher-worker-3 @coroutine#6] DEBUG async-tls/1 - handshake completed
        18:23:23.998 [DefaultDispatcher-worker-3 @coroutine#6] DEBUG async-tls/1 - transitioning [handshaking -> connected] 
        18:23:24.017 [DefaultDispatcher-worker-3 @coroutine#7] TRACE async-tls/1 - ssl state Status = OK HandshakeStatus = NOT_HANDSHAKING
        bytesConsumed = 24 bytesProduced = 53 sequenceNumber = 1
        18:23:24.019 [DefaultDispatcher-worker-3 @coroutine#8] TRACE async-tls/1 - ssl state Status = OK HandshakeStatus = NOT_HANDSHAKING
        bytesConsumed = 15 bytesProduced = 44 sequenceNumber = 2
        18:23:24.019 [DefaultDispatcher-worker-3 @coroutine#9] TRACE async-tls/1 - ssl state Status = OK HandshakeStatus = NOT_HANDSHAKING
        bytesConsumed = 13 bytesProduced = 42 sequenceNumber = 3
        18:23:24.030 [DefaultDispatcher-worker-1 @coroutine#11] TRACE async-tls/1 - ssl state Status = OK HandshakeStatus = NOT_HANDSHAKING
        bytesConsumed = 357 bytesProduced = 386 sequenceNumber = 4
        18:23:24.040 [DefaultDispatcher-worker-1 @coroutine#13] TRACE async-tls/1 - ssl state Status = OK HandshakeStatus = NOT_HANDSHAKING
        bytesConsumed = 9 bytesProduced = 38 sequenceNumber = 5
        18:23:24.539 [DefaultDispatcher-worker-1 @coroutine#3] ERROR Controller - error: HTTP 401 
        18:23:24.541 [DefaultDispatcher-worker-1 @coroutine#3] WARN Controller - request failed with Error(code=INVALID_AUTH, message=The authentication request failed, cause=null, field=null)
        18:23:24.543 [DefaultDispatcher-worker-1 @coroutine#3] ERROR ZitiContextImpl - failed to login, cannot continue
        18:23:24.544 [DefaultDispatcher-worker-2 @coroutine#2] DEBUG ZitiContextImpl - 3zIUuFGBC[null]@https://23.22.127.125:443 transitioned to NotAuthorized
        Exception in thread "DefaultDispatcher-worker-1 @coroutine#3" org.openziti.ZitiException: NotAuthorized: HTTP 401 
	        at org.openziti.api.Controller.convertError(Controller.kt:255)
	        at org.openziti.api.Controller.login$ziti(Controller.kt:157)
	        at org.openziti.api.Controller$login$1.invokeSuspend(Controller.kt)
	        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
        Caused by: retrofit2.HttpException: HTTP 401 
	        at com.jakewharton.retrofit2.adapter.kotlin.coroutines.CoroutineCallAdapterFactory$BodyCallAdapter$adapt$2.onResponse(CoroutineCallAdapterFactory.kt:104)
	        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
	        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
	        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	        at java.base/java.lang.Thread.run(Thread.java:834)
        18:23:28.018 [main] DEBUG ZitiContextImpl - stopping networking
        18:23:28.020 [main] DEBUG ZitiContextImpl - stopping controller
        18:23:28.021 [main] DEBUG ZitiContextImpl - shutting down
        18:23:28.029 [main] DEBUG ZitiContextImpl - ziti context is finished

**Comment by ekoby** [comment]
if endpoint already registered you can not enroll again

**Comment by ekoby** [comment]
works as it should
