### ISSUE TITLE
Whether to intercept traffic globally

### ISSUE THREAD

**Issue by five131415** [openziti/ziti-sdk-jvm#422]
After embedding this sdk, will the global traffic of the entire mobile phone go through the Ziti network? Or only the current app
Also, after embedding this sdk, can it intercept a specified app on the mobile phone from going to the ziti network, or a specific ip/domain from going to the ziti network

**Comment by ekoby** [comment]
No. Only domain names and IPs for services that your identity has access too will go over Ziti network. All other addresses will connect directly.

**Comment by five131415** [comment]
> No. Only domain names and IPs for services that your identity has access too will go over Ziti network. All other addresses will connect directly.

Thank you.
